#! /bin/bash

# Bash interface to the PushBullet api.

# Author: Red5d - https://github.com/Red5d


CONFIG=${XDG_CONFIG_HOME:-$HOME/.config}/pushbullet
API_URL=https://www.pushbullet.com/api

source $CONFIG

if [ "$1" = "" ];then

if [ "$API_KEY" = "" ];then
echo -e "\e[0;33mWarning, your API key is not set.\nPlease create $CONFIG with a line starting with API_KEY= and your PushBullet key\e[00m"
fi

cat << EOF
Usage: pushbullet <action> <device> <type> <data>

Actions: 
list - Lists all devices in your PushBullet account. (does not require additional parameters)
push - Pushes data to a device. (the device name can simply be a unique part of the name that "list" returns)

Types: 
note
address
file
link

Type Parameters: 
(all parameters must be put inside quotes if more than one word)
"note" type: 	give the title, then the note text.
"address" type: give the address name, then the address or Google Maps query.
"list" type: 	give the name of the list, then each of the list items, separated by spaces.
"file" type: 	give the path to the file.
"link" type: 	give the title of the link, then the url.

EOF
exit
fi

case $1 in
list)
	curl -s "$API_URL/devices" -u $API_KEY: | sed 's/{\"id/\n{\"id/g' | cut -d'"' -f12
	;;
push)

	dev_id=$(curl -s "$API_URL/devices" -u $API_KEY: | sed 's/{\"id/\n{\"id/g' | grep -i $2 | cut -d: -f2 | cut -d, -f1)

	case $3 in
	note)

		curl -s "$API_URL/pushes" -u $API_KEY: -d device_id=$dev_id -d type=note -d body="$4" | cut -d'"' -f10,20 | tr '"' ' '

	;;

	address)

		curl -s "$API_URL/pushes" -u $API_KEY: -d device_id=$dev_id -d type=address -d name="$4" -d address="$5" | cut -d'"' -f10,20 | tr '"' ' '

	;;

	list)

	 argnum=0
        for i in $@
        do
          let argnum=$argnum+1
          if [ $argnum -ge 5 ];then
            itemlist=$itemlist" -d items="$i
          fi
        done
	curl -s $API_URL/pushes -u $API_KEY: -d device_id=$dev_id -d type=list -d title=$4 $itemlist | cut -d'"' -f10,14 | tr '"' ' '

	;;

	file)

		curl -s "$API_URL/pushes" -u $API_KEY: -F device_id=$dev_id -F type=file -F file="@$4" -X POST | cut -d'"' -f10,24 | tr '"' ' '

	;;

	link)

		curl -s "$API_URL/pushes" -u $API_KEY: -d device_id=$dev_id -d type=link -d title="$4" -d url="$5" | cut -d'"' -f10,20 | tr '"' ' '

	;;
	esac

;;

*)
  cat << EOF
Usage: pushbullet <action> <device> <type> <data>

Actions: 
list - Lists all devices in your PushBullet account. (does not require additional parameters)
push - Pushes data to a device. (the device name can simply be a unique part of the name that "list" returns)

Types: 
note
address
file
link

Type Parameters: 
(all parameters must be put inside quotes if more than one word)
"note" type: 	give the title, then the note text.
"address" type: give the address name, then the address or Google Maps query.
"list" type: 	give the name of the list, then each of the list items, separated by spaces.
"file" type: 	give the path to the file.
"link" type: 	give the title of the link, then the url.

EOF
;;
esac
